### ISSUE TITLE
Make cards clickable (and pretty) in MyJourneys

### ISSUE THREAD

**Issue by jpushkarskaya** [ParanoidAndroid3/Journey#10]
- Allow background photo (google search)
- On click expand card to navigate to map view

**Comment by jpushkarskaya** [comment]
Assigning to you @emaccaull, since you've been working on it.

**Comment by jkoryf** [comment]
- Background photo implemented on feature/myjourneys-images merge.

Will move "On click expand card to navigate to map view" to Sprint 3
