### ISSUE TITLE
Fix incorrect leg duration in My Journeys

### ISSUE THREAD

**Issue by emaccaull** [ParanoidAndroid3/Journey#46]
This is a side effect of the way that dates are saved in the wizard.

We have the choice of doing something in the wizard or fudging the DateFormattingUtils#formatDurationInDays() and always adding 1 to the day.

Bonus: some care needs to be taken to ensure that the date ranges will be correct even when changing time zones.

**Comment by jkoryf** [comment]
+1 for the time zone changes, this needs adjustments also in planner.

I would say go with adding one day to what you get from the util for now.
